name: Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test-lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Deps
        uses: swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --all-features --verbose

      - name: Format (rustfmt)
        run: cargo fmt --verbose

      - name: Lint (clippy)
        run: cargo clippy --release --verbose

      - name: Test
        run: cargo test --release --verbose
